version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2-arm64
    restart: always
    container_name: elasticsearch
    volumes:
      - ./src/main/java/com/trendyTracker/infrastructure/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=tech_frontier_by_software_engine
    ports:
      - "9200:9200"
