version: '3.8'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.5.1
    ports:
      - '00000:00000'
    environment:
      ZOOKEEPER_CLIENT_PORT: 
      ZOOKEEPER_TICK_TIME: 

  kafka-1:
    image: confluentinc/cp-kafka:5.5.1
    ports:
      - '0000:0000'
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID:
      KAFKA_ZOOKEEPER_CONNECT: 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
      KAFKA_INTER_BROKER_LISTENER_NAME:
      KAFKA_ADVERTISED_LISTENERS:
      KAFKA_DEFAULT_REPLICATION_FACTOR:
      KAFKA_NUM_PARTITIONS: 

  kafka-2:
    image: confluentinc/cp-kafka:5.5.1
    ports:
      - '0000:0000'
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID:
      KAFKA_ZOOKEEPER_CONNECT: 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
      KAFKA_INTER_BROKER_LISTENER_NAME:
      KAFKA_ADVERTISED_LISTENERS:
      KAFKA_DEFAULT_REPLICATION_FACTOR: 
      KAFKA_NUM_PARTITIONS: 

  kafka-3:
    image: confluentinc/cp-kafka:5.5.1
    ports:
      - '0000:0000'
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 
      KAFKA_ZOOKEEPER_CONNECT: 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 
      KAFKA_INTER_BROKER_LISTENER_NAME:
      KAFKA_ADVERTISED_LISTENERS: 
      KAFKA_DEFAULT_REPLICATION_FACTOR: 
      KAFKA_NUM_PARTITIONS: 

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "0000:0000"
    restart: always
    depends_on:
      - zookeeper-1
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:00000,kafka-2:00000,kafka-3:00000
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-1:00000
