version: '3.3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.1.2-arm64
    container_name: logstash
    volumes:
      - ./src/main/java/com/trendyTracker/common/logstash:/usr/share/logstash/config
    networks:
      - elk-network


  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.2-arm64
    container_name: kibana
    volumes:
      - ./src/main/java/com/trendyTracker/common/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - elk-network


  trendy_tracker:
    image: jinsujj/trendy-tracker-backend:latest
    ports:
      - '8080:8080'
    restart: always
    container_name: trendy_tracker
    depends_on:
      - zookeeper-1
      - kafka-1
      - kafka-2
      - kibana
    network_mode: host
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://000.0.00.000:0000/
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_DATASOURCE_DRIVER_CLASS_NAME:  org.postgresql.Driver
      TOKEN_VALUE: 
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_HIBERNATE_SHOW_SQL: "off"
      SPRING_JPA_HIBERNATE_FORMAT_SQL: "off"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092,localhost:9093,localhost:9094
      LOGGING_LEVEL_ORG_APACHE_KAFKA: "off"


  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.2.2.arm64
    ports:
      - '32181:32181'
    networks:
      - elk-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000


  kafka-1:
    image: confluentinc/cp-kafka:7.2.2.arm64
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper-1
    networks:
      - elk-network
    container_name: kafka-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3


  kafka-2:
    image: confluentinc/cp-kafka:7.2.2.arm64
    ports:
      - '9093:9093'
    depends_on:
      - zookeeper-1
    networks:
      - elk-network
    container_name: kafka-2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29093,EXTERNAL://localhost:9093
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
    
  kafka-3:
    image: confluentinc/cp-kafka:7.2.2.arm64
    ports:
      - '9094:9094'
    depends_on:
      - zookeeper-1
    networks:
      - elk-network
    container_name: kafka-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29094,EXTERNAL://localhost:9094
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8989:8080"
    restart: always
    depends_on:
      - zookeeper-1
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - elk-network
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:29092 ,kafka-2:29093,kafka-3:29094
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-1:22181

networks:
  elk-network:
    driver: bridge
