version: '3.3'

networks: 
  my_network: 
    driver: bridge

services:
  trendy_tracker:
    image: jinsujj/trendy-tracker-backend:latest
    networks:
      - my_network
    ports:
      - '8080:8080'
    restart: always
    container_name: trendy_tracker
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://000.0.00.000:0000/
      SPRING_DATASOURCE_USERNAME:  
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_DATASOURCE_DRIVER_CLASS_NAME:  org.postgresql.Driver
      TOKEN_VALUE: 
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_HIBERNATE_SHOW_SQL: "off"
      SPRING_JPA_HIBERNATE_FORMAT_SQL: "off"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092,localhost:9093,localhost:9094
      LOGGING_LEVEL_ORG_APACHE_KAFKA: "off"
      MAIL_HOST: smtp.daum.net
      MAIL_PORT: 465
      MAIL_USERNAME: 
      MAIL_PASSWORD: 
      MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      MAIL_PROPERTIES_MAIL_SMTP_AUTH:  "true"
      JWT_SECRET_KEY: 


  trendy_tracker2:
    image: jinsujj/trendy-tracker-backend:latest
    networks:
      - my_network
    ports:
      - '8081:8081'
    restart: always
    container_name: trendy_tracker2
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://000.0.00.000:0000/
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD:  
      SPRING_DATASOURCE_DRIVER_CLASS_NAME:  org.postgresql.Driver
      TOKEN_VALUE: 
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_HIBERNATE_SHOW_SQL: "off"
      SPRING_JPA_HIBERNATE_FORMAT_SQL: "off"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092,localhost:9093,localhost:9094
      LOGGING_LEVEL_ORG_APACHE_KAFKA: "off"
      MAIL_HOST: smtp.daum.net
      MAIL_PORT: 465
      MAIL_USERNAME: 
      MAIL_PASSWORD: 
      MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      MAIL_PROPERTIES_MAIL_SMTP_AUTH:  "true"
      JWT_SECRET_KEY: 
