server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://110.8.21.243:5432/trendy_tracker
    username: trendy_tracker
    password: Init1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: false

mail:
  host: smtp.daum.net
  port: 465
  username: creaticoding@daum.net
  password: "@@trendy-tracker@@nknk"
  properties:
    mail:
      smtp:
        starttls:
          enable: true
        auth: true

token:
  value: RAs7uvb92vbgf7xAvJQmXM697H*WMf44a9tTi*

logging:
  level:
    org.apache.kafka: off

kafka:
  bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
