server:
  port: 8080

spring:
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: 
  jpa:
    hibernate:
      ddl-auto:
    show-sql: false
    properties:
      hibernate.format_sql: false

mail:
  host:
  port: 
  username: 
  password: 
  properties:
    mail:
      smtp:
        starttls:
          enable: true
        auth: true

jwt:
  secret_key: 

token:
  value: 

logging:
  level:
    org.apache.kafka: off

kafka:
  bootstrap-servers: 

redis:
  host: 
  port: 
