server:
  port: 

spring:
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: 
  jpa:
    hibernate:
      ddl-auto:
    show-sql: false
    properties:
      hibernate.format_sql: false

token:
  value: 

logging:
  level:
    org.apache.kafka: off

kafka:
  bootstrap-servers: 
