server:
  port:
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto:
      hibernate:
        show_sql:
        format_sql:
token:
  value:
logging:
  level:
    org.apache.kafka:
