server:
  port:
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
docker_hub:
  username:
  password:
