name: Spring Boot & Gradle CI/CD

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Install chromium and chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium
          sudo apt-get install -y chromium-driver
          sudo apt-get install -y openjdk-17-jdk
          echo "JAVA_HOME=$(readlink -f /usr/bin/javac | sed 's:/bin/javac::')" | sudo tee -a /etc/environment
          source /etc/environment

      - uses: actions/checkout@v3
      - name: Create application.yml
        run: |
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
          cat ./src/main/resources/application.yml

      # - name: Copy chromedriver binary
      #   run: |
      #     cp /app/chromedriver/chromedriver /usr/local/bin/
      
      - name: Make gradlew executable and build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon 
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: jinsujj/trendy-tracker-backend:latest
