name: Spring Boot & Gradle CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: "adopt"
          java-version: "17"

      - uses: actions/checkout@v3
      - name: Create application.yml
        run: |
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
          cat ./src/main/resources/application.yml

      - name: Set up QEMU
        run: |
          docker run --rm --privileged aptman/qus -s -- -p aarch64

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew clean build

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./src/build
          push: true
          tags: jinsujj/trendy-tracker-backend:latest
