name: Spring Boot & Gradle CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          architecture: 'aarch64'

      - name: Install chromium and chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium
          sudo apt-get install -y chromium-driver

      - uses: actions/checkout@v3

      - name: Create application.yml
        run: |
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
          cat ./src/main/resources/application.yml

      - name: Grant execute permission to Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Clear Docker build cache
        run: docker builder prune -a -f

      - name: Build and push with unique tag
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: jinsujj/trendy-tracker-backend:${{ github.sha }}
